updated lf config remove ueberzug

diff --git a/config/lf/preview b/config/lf/preview
--- a/config/lf/preview
+++ b/config/lf/preview
@@ -1,55 +1,61 @@
 #!/bin/sh
+file=$1
+w=$2
+h=$3
+x=$4
+y=$5
 
-image() {
-	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
-		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
-	else
-		mediainfo "$6"
-	fi
+# making thumbnails folder if it doesnt exist
+if [ ! -d "$HOME/.cache/thumbnails" ]; then
+    mkdir -p "$HOME/.cache/thumbnails"
+  else
+    rm -rf "$HOME/.cache/thumbnails"/*
+fi
+
+TEMPDIR=~/.cache/thumbnails
+
+preview() {
+    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
+    exit 1
 }
 
-
-
-CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
-
-case "$(printf "%s\n" "$(readlink -f "$1")" | tr '[:upper:]' '[:lower:]')" in
-    *.tgz | *.tar.gz) tar tzf "$1" ;;
-    *.tar.bz2 | *.tbz2) tar tjf "$1" ;;
-    *.tar.txz | *.txz) xz --list "$1" ;;
-    *.tar) tar tf "$1" ;;
-    *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$1" ;;
-    *.rar) unrar l "$1" ;;
-    *.7z) 7z l "$1" ;;
-    *.[1-8]) man "$1" | col -b ;;
-    *.o) nm "$1" ;;
-    *.torrent) transmission-show "$1" ;;
-    *.iso) iso-info --no-header -l "$1" ;;
-    *.odt | *.ods | *.odp | *.sxw) odt2txt "$1" ;;
-    *.doc) catdoc "$1" ;;
-    *.docx) docx2txt "$1" - ;;
+file="$1"; shift
+case "$(basename "$file" | tr '[A-Z]' '[a-z]')" in
+    *.tgz | *.tar.gz) tar tzf "$file" ;;
+    *.tar.bz2 | *.tbz2) tar tjf "$file" ;;
+    *.tar.txz | *.txz) xz --list "$file" ;;
+    *.tar) tar tf "$file" ;;
+    *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$file" ;;
+    *.rar) unrar l "$file" ;;
+    *.7z) 7z l "$file" ;;
+    *.[1-8]) man "$file" | col -b ;;
+    *.o) nm "$file" ;;
+    *.odt | *.ods | *.odp | *.sxw) odt2txt "$file" ;;
+    *.doc) catdoc "$file" ;;
+    *.docx) docx2txt "$file" - ;;
     *.xls | *.xlsx)
-        ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batcat --language=csv
-        ;;
+         ssconvert --export-type=Gnumeric_stf:stf_csv "$file" "fd://1" | cat --language=csv
+         ;;
     *.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx] | *.mka)
-        mediainfo "$1"
-        ;;
-    *.pdf)
-         pdftoppm -jpeg -f 1 -singlefile "$1"
-        image "$1" "$2" "$3" "$4" "$5"
-        ;;
+         mediainfo "$file"
+         ;;
     *.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
-        [ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
-        image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
-        ;;
+    thumbnail="$TEMPDIR/thumbnail.jpg"
+    ffmpegthumbnailer -i "$file" -o  "$thumbnail" -s 0 -q 5
+    preview "$thumbnail"
+	;;
+    *.pdf)
+    thumbnail="$TEMPDIR/thumbnail.jpg"
+	gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
+	preview "$thumbnail"
+	;;
     *.bmp | *.jpg | *.jpeg | *.png | *.xpm | *.webp | *.gif | *.jfif)
-        image "$1" "$2" "$3" "$4" "$5"
-        ;;
+    preview "$file"
+    ;;
     *.svg)
-        [ ! -f "${CACHE}.jpg" ] && convert "$1" "${CACHE}.jpg"
-        image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
-        ;;
-    *)
-        batcat "$1"
-        ;;
+	preview "$file"
+	;;
+    *) 
+    cat "$file" ;;
 esac
-exit RGBA_16
+return 127 # nonzero retcode required for lf previews to reload
